vim.opt.number = true -- show line numbers
vim.opt.expandtab = true -- use spaces for indentation
vim.opt.shiftwidth = 2 -- number of spaces for each indentation
vim.opt.tabstop = 2 -- number of spaces for tab character
vim.opt.softtabstop = 2 -- number of spaces for tab character (when editing)
vim.opt.smartindent = true -- enable smart indentation
vim.g.netrw_banner = 0 -- disbable banner for explorer
vim.g.netrw_liststyle = 3 -- type of list for explorer
vim.g.netrw_winsize = 30 -- set maximum size of the explorer window
